"""
Generated By: Cursor (Claude Sonnet 4.5)

Pytest configuration and shared fixtures for ap-fits-headers tests.
"""

import shutil
import tempfile
from pathlib import Path

import pytest

# Path to fixtures directory containing real test files
FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _is_lfs_pointer(filepath: Path) -> bool:
    """Check if a file is a Git LFS pointer instead of actual content."""
    try:
        with open(filepath, "rb") as f:
            header = f.read(100)
            # LFS pointers start with "version https://git-lfs"
            return header.startswith(b"version https://git-lfs")
    except Exception:
        return False


@pytest.fixture
def temp_dir():
    """Create a temporary directory for tests."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def sample_fits_file(temp_dir):
    """
    Provide a real FITS file for testing.

    Copies the real FITS file from tests/fixtures/ to a temporary directory
    to ensure the source file remains immutable.
    """
    source_file = FIXTURES_DIR / "sample.fits"
    if not source_file.exists():
        pytest.skip(
            f"Real FITS fixture file not found: {source_file}. "
            f"Please add a real FITS file to {FIXTURES_DIR} and track it with git LFS."
        )

    if _is_lfs_pointer(source_file):
        pytest.skip(
            "FITS fixture is a Git LFS pointer. Run 'git lfs pull' to fetch actual files."
        )

    # Copy to temp directory to keep source immutable
    fits_path = temp_dir / "test.fits"
    shutil.copy2(source_file, fits_path)
    return fits_path


@pytest.fixture
def sample_xisf_file(temp_dir):
    """
    Provide a real XISF file for testing.

    Copies the real XISF file from tests/fixtures/ to a temporary directory
    to ensure the source file remains immutable.
    """
    source_file = FIXTURES_DIR / "sample.xisf"
    if not source_file.exists():
        pytest.skip(
            f"Real XISF fixture file not found: {source_file}. "
            f"Please add a real XISF file to {FIXTURES_DIR} and track it with git LFS."
        )

    if _is_lfs_pointer(source_file):
        pytest.skip(
            "XISF fixture is a Git LFS pointer. Run 'git lfs pull' to fetch actual files."
        )

    # Copy to temp directory to keep source immutable
    xisf_path = temp_dir / "test.xisf"
    shutil.copy2(source_file, xisf_path)
    return xisf_path
